import Restaurant from "../models/restaurant.model.js";
import Menu from "../models/menu.model.js";
import User from "../models/user.model.js";

export const getRestaurantsSeedData = (managerMap) => [
  // 1. Bella Napoli Pizzeria & Trattoria
  {
    restaurant: {
      managerId: managerMap["manager1@gmail.com"],
      restaurantName: "Bella Napoli Pizzeria & Trattoria",
      description: "Authentic Neapolitan wood-fired artisanal pizzas, hand-crafted pastas, fresh burrata salads, and decadent Italian desserts prepared with imported San Marzano tomatoes and extra virgin olive oil.",
      address: "Shop 14-16, Gourmet Galleria, University Avenue",
      city: "Campus Central",
      state: "Metro",
      pinCode: "560001",
      country: "India",
      geoLocation: { lat: "12.9716", lon: "77.5946" },
      contactDetails: { email: "contact@bellanapoli.com", phone: "+91 98765 43201" },
      servingHours: { openingTime: "11:00", closingTime: "23:30" },
      isOpen: true,
      status: "active",
      averageRating: 4.8,
      cuisineTypes: ["Italian", "Wood-Fired Pizza", "Pasta", "Garlic Breads", "Desserts"],
      restaurantType: "both",
      coverImage: {
        url: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1200&q=80",
        publicId: null,
      },
      restaurantImage: [
        { url: "https://images.unsplash.com/photo-1579684947550-22e945225d9a?auto=format&fit=crop&w=800&q=80", publicId: null },
        { url: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80", publicId: null },
        { url: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=80", publicId: null },
      ],
      socialMediaLinks: [
        { platform: "Instagram", url: "https://instagram.com/bellanapolicravings" },
        { platform: "Facebook", url: "https://facebook.com/bellanapolipizza" },
      ],
      documents: {
        legalName: "Bella Napoli Hospitality Pvt Ltd",
        companyType: "Private Limited",
        gstCertificate: "29AABCU9603R1ZM",
        fssaiCertificate: "11223344556677",
        panCard: "AABCU9603R",
      },
      financialDetails: {
        bankName: "HDFC Bank",
        accountNumber: "50200012345678",
        ifscCode: "HDFC0001234",
      },
    },
    menuItems: [
      {
        itemName: "Margherita Classica",
        description: "Italian San Marzano tomato sauce, fresh buffalo mozzarella, aromatic basil, and a drizzle of extra virgin olive oil.",
        price: 349,
        category: "Pizzas",
        foodType: "Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Quattro Formaggi",
        description: "Four cheese heaven with creamy gorgonzola, aged parmesan, mozzarella, and artisanal ricotta on a crispy crust.",
        price: 449,
        category: "Pizzas",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1573821663912-569905455b1c?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Fiery Pepperoni & Salami Rustica",
        description: "Loaded with smoky cured pork pepperoni, spicy salami, crushed red chili flakes, and melted smoked scamorza.",
        price: 499,
        category: "Pizzas",
        foodType: "Non-Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Truffle Wild Mushroom Pizza",
        description: "Sauteed shiitake, button and portobello mushrooms, garlic confit, white truffle oil, and fresh thyme.",
        price: 479,
        category: "Pizzas",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: false,
        isNew: true,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Creamy Pesto Penne Alla Genovese",
        description: "Al dente penne tossed in rich basil pine nut pesto, sun-dried tomatoes, toasted walnuts, and shaved Grana Padano.",
        price: 389,
        category: "Pastas",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1621996346565-e3d5d6281691?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Fettuccine Alfredo with Herb Grilled Chicken",
        description: "Classic creamy parmesan and butter sauce gently coating fresh fettuccine with garlic-herb grilled chicken tenders.",
        price: 429,
        category: "Pastas",
        foodType: "Non-Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Cheesy Pull-Apart Garlic Loaf",
        description: "Freshly baked sourdough loaf stuffed with roasted garlic butter, parsley, and gooey melted mozzarella.",
        price: 199,
        category: "Starters & Breads",
        foodType: "Vegetarian",
        isTopRated: true,
        isRecommended: false,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1619535860434-ba1d8fa12536?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Classic Bruschetta al Pomodoro",
        description: "Toasted country bread topped with diced ripe Roma tomatoes, garlic, extra virgin olive oil, basil, and balsamic reduction.",
        price: 229,
        category: "Starters & Breads",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: false,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Tiramisu Classico",
        description: "Traditional Italian dessert of espresso-soaked savoiardi ladyfingers layered with rich mascarpone zabaglione and cocoa.",
        price: 269,
        category: "Desserts",
        foodType: "Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Italian Peach & Mint Iced Tea",
        description: "Chilled black tea infused with natural white peach puree, crushed mint leaves, and lemon zest.",
        price: 149,
        category: "Beverages",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: false,
        isNew: true,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
    ],
  },

  // 2. The Burger Barn & Smokehouse
  {
    restaurant: {
      managerId: managerMap["manager2@gmail.com"],
      restaurantName: "The Burger Barn & Smokehouse",
      description: "Juicy double smash burgers, crispy Nashville hot chicken, hand-cut seasoned fries, smoky barbecue platters, and thick gourmet milkshakes designed for late-night cravings.",
      address: "Plot 8, North Gate Commercial Strip, Student Hub",
      city: "Campus North",
      state: "Metro",
      pinCode: "560002",
      country: "India",
      geoLocation: { lat: "12.9812", lon: "77.6015" },
      contactDetails: { email: "orders@theburgerbarn.com", phone: "+91 98765 43202" },
      servingHours: { openingTime: "10:30", closingTime: "01:00" },
      isOpen: true,
      status: "active",
      averageRating: 4.7,
      cuisineTypes: ["Burgers", "American", "Crispy Fries", "Wraps", "Shakes"],
      restaurantType: "both",
      coverImage: {
        url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=80",
        publicId: null,
      },
      restaurantImage: [
        { url: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80", publicId: null },
        { url: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80", publicId: null },
      ],
      socialMediaLinks: [
        { platform: "Instagram", url: "https://instagram.com/burgerbarnsmoke" },
      ],
      documents: {
        legalName: "Barn Foods and Hospitality LLP",
        companyType: "LLP",
        gstCertificate: "29BBBCU9604R1ZN",
        fssaiCertificate: "11223344556688",
        panCard: "BBBCU9604R",
      },
      financialDetails: {
        bankName: "ICICI Bank",
        accountNumber: "001105001234",
        ifscCode: "ICIC0000011",
      },
    },
    menuItems: [
      {
        itemName: "Classic Double Smash Cheeseburger",
        description: "Two crispy-edged seared beef/buff patties, double melted Wisconsin cheddar, pickles, grilled onions, and house barn sauce on toasted brioche.",
        price: 299,
        category: "Burgers",
        foodType: "Non-Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Nashville Hot Fried Chicken Burger",
        description: "Spicy buttermilk-fried chicken breast tossed in cayenne oil glaze, dill pickles, and creamy creamy ranch slaw.",
        price: 329,
        category: "Burgers",
        foodType: "Non-Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Truffle Portobello & Gouda Burger",
        description: "Crisp panko-crusted portobello mushroom stuffed with gouda cheese, caramelized balsamic onions, and garlic truffle aioli.",
        price: 279,
        category: "Burgers",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: true,
        isNew: true,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1520072959219-c595dc870360?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Loaded Truffle & Parmesan Fries",
        description: "Crisp skin-on Idaho fries tossed with white truffle oil, rosemary sea salt, grated aged parmesan, and garlic mayo dip.",
        price: 189,
        category: "Fries & Sides",
        foodType: "Vegetarian",
        isTopRated: true,
        isRecommended: false,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Crispy Cajun Chicken Tenders (6 pcs)",
        description: "Golden crumb-fried spiced chicken tenderloins served with honey mustard and smoky chipotle barbecue sauce.",
        price: 249,
        category: "Fries & Sides",
        foodType: "Non-Vegetarian",
        isTopRated: false,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Smoky Peri Peri Chicken Wrap",
        description: "Flame-grilled peri-peri chicken strips, roasted bell peppers, cheddar melt, and mint mayo in a toasted tortilla.",
        price: 239,
        category: "Wraps & Rolls",
        foodType: "Non-Vegetarian",
        isTopRated: false,
        isRecommended: false,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Crispy Paneer Tikka Wrap",
        description: "Tandoori spiced paneer cubes, crunchy iceberg, pickled red onions, and zesty chipotle dip wrapped in a flatbread.",
        price: 219,
        category: "Wraps & Rolls",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: false,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1644704170910-a0cdf183649b?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Thick Belgian Dark Chocolate Shake",
        description: "Rich dark chocolate ice cream blended with crushed brownie bites, fudge sauce, and whipped cream topping.",
        price: 189,
        category: "Shakes & Beverages",
        foodType: "Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Salted Caramel Pretzel Shake",
        description: "Caramelized dulce de leche shake topped with crunchy salted pretzels and butterscotch sprinkles.",
        price: 199,
        category: "Shakes & Beverages",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: true,
        isNew: true,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1541658016709-82535e94bc69?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
    ],
  },

  // 3. Royal Biryani & Mughlai Darbar
  {
    restaurant: {
      managerId: managerMap["manager3@gmail.com"],
      restaurantName: "Royal Biryani & Mughlai Darbar",
      description: "Authentic slow-cooked Hyderabadi Dum Biryani, royal Awadhi kebabs, melt-in-mouth Butter Chicken, and aromatic Nizami gravies made using age-old royal recipes and fragrant saffron.",
      address: "Palace Road, Opposite University Clock Tower",
      city: "Campus South",
      state: "Metro",
      pinCode: "560003",
      country: "India",
      geoLocation: { lat: "12.9640", lon: "77.5850" },
      contactDetails: { email: "royalbiryani@darbarcravings.com", phone: "+91 98765 43203" },
      servingHours: { openingTime: "11:30", closingTime: "23:30" },
      isOpen: true,
      status: "active",
      averageRating: 4.9,
      cuisineTypes: ["Mughlai", "Hyderabadi Biryani", "North Indian", "Kebabs", "Curries"],
      restaurantType: "both",
      coverImage: {
        url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=1200&q=80",
        publicId: null,
      },
      restaurantImage: [
        { url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80", publicId: null },
        { url: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80", publicId: null },
      ],
      socialMediaLinks: [
        { platform: "Instagram", url: "https://instagram.com/royalbiryaniofficial" },
      ],
      documents: {
        legalName: "Mughlai Darbar Hospitality Services",
        companyType: "Partnership",
        gstCertificate: "29CCCU9605R1ZO",
        fssaiCertificate: "11223344556699",
        panCard: "CCCU9605R",
      },
      financialDetails: {
        bankName: "State Bank of India",
        accountNumber: "305011223344",
        ifscCode: "SBIN0001234",
      },
    },
    menuItems: [
      {
        itemName: "Hyderabadi Dum Gosht Biryani",
        description: "Tender pieces of spring mutton slow cooked on charcoal 'dum' with long-grain aged Basmati rice, saffron, and rich spices. Served with spicy Mirchi Ka Salan and Raita.",
        price: 449,
        category: "Biryani Special",
        foodType: "Non-Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Shahi Dum Chicken Biryani",
        description: "Succulent chicken drumsticks marinated in aromatic spices, brown onions, mint, and saffron layered with fragrant Basmati rice.",
        price: 349,
        category: "Biryani Special",
        foodType: "Non-Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Royal Subz Paneer Dum Biryani",
        description: "Fresh garden vegetables, marinated cottage cheese cubes, saffron, fried cashews, and aromatic herbs cooked under sealed handi dum.",
        price: 299,
        category: "Biryani Special",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1642821373181-696a54913e9a?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Murgh Makhani (Butter Chicken)",
        description: "Tender tandoor-roasted chicken simmered in a silky tomato, cashew, and butter gravy seasoned with dried fenugreek leaves (kasoori methi).",
        price: 379,
        category: "Mughlai Curries",
        foodType: "Non-Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Paneer Lababdar",
        description: "Soft cottage cheese chunks and grated paneer cooked in a rich, mildly spiced onion-tomato and melon seed gravy.",
        price: 329,
        category: "Mughlai Curries",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1567184109411-b28f2703e1cd?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Dal Makhani Bukhara Style",
        description: "Whole black lentils slow cooked overnight on charcoal with butter, cream, and subtle smoky spices.",
        price: 269,
        category: "Mughlai Curries",
        foodType: "Vegetarian",
        isTopRated: true,
        isRecommended: false,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Galouti Kebab with Mughlai Paratha",
        description: "Melt-in-mouth smoked lamb patties infused with 32 royal spices, served on mini saffron parathas with mint chutney.",
        price: 369,
        category: "Kebabs & Tandoor",
        foodType: "Non-Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Dahi Ke Kebab (Crispy Hung Curd Kebabs)",
        description: "Golden-crusted croquettes made of hung curd, green chilies, coriander, and crushed spices.",
        price: 249,
        category: "Kebabs & Tandoor",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: false,
        isNew: true,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Garlic Butter Naan",
        description: "Soft leavened tandoor-baked flatbread brushed with garlic butter and fresh coriander.",
        price: 69,
        category: "Tandoori Breads",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: false,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1601050690187-5c5f85e4ea74?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Shahi Tukda with Rabdi",
        description: "Crisp fried bread soaked in saffron sugar syrup and layered with thickened creamy rabdi and slivered pistachios.",
        price: 179,
        category: "Desserts",
        foodType: "Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
    ],
  },

  // 4. Wok & Roll Asian Kitchen
  {
    restaurant: {
      managerId: managerMap["manager4@gmail.com"],
      restaurantName: "Wok & Roll Asian Kitchen",
      description: "Steaming crystal dim sums, sizzling wok-tossed Hakka noodles, authentic Pad Thai, Thai Green curry bowls, and crisp Asian street delicacies.",
      address: "Floor 2, East Square Food Court, Tech Hub",
      city: "Campus East",
      state: "Metro",
      pinCode: "560004",
      country: "India",
      geoLocation: { lat: "12.9750", lon: "77.6100" },
      contactDetails: { email: "hi@wokandrollasian.com", phone: "+91 98765 43204" },
      servingHours: { openingTime: "12:00", closingTime: "23:00" },
      isOpen: true,
      status: "active",
      averageRating: 4.6,
      cuisineTypes: ["Pan-Asian", "Chinese", "Dim Sum", "Noodles", "Thai"],
      restaurantType: "both",
      coverImage: {
        url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1200&q=80",
        publicId: null,
      },
      restaurantImage: [
        { url: "https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?auto=format&fit=crop&w=800&q=80", publicId: null },
        { url: "https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=800&q=80", publicId: null },
      ],
      socialMediaLinks: [
        { platform: "Instagram", url: "https://instagram.com/wokandrollcravings" },
      ],
      documents: {
        legalName: "Wok & Roll Foods Pvt Ltd",
        companyType: "Private Limited",
        gstCertificate: "29DDCU9606R1ZP",
        fssaiCertificate: "11223344556700",
        panCard: "DDCU9606R",
      },
      financialDetails: {
        bankName: "Axis Bank",
        accountNumber: "919020012345678",
        ifscCode: "UTIB0001234",
      },
    },
    menuItems: [
      {
        itemName: "Steamed Chicken & Basil Dim Sum (6 pcs)",
        description: "Thin translucent dumplings filled with seasoned minced chicken, Thai holy basil, and water chestnuts, served with spicy scallion chili dip.",
        price: 289,
        category: "Dim Sum & Baos",
        foodType: "Non-Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Crystal Truffle & Edamame Dumpling (6 pcs)",
        description: "Artisanal vegetarian dumplings stuffed with mashed edamame, wild mushrooms, and fragrant truffle essence.",
        price: 319,
        category: "Dim Sum & Baos",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: true,
        isNew: true,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Hakka Chili Garlic Wok Noodles",
        description: "Street-style egg/wheat noodles tossed on high flame with crunchy bell peppers, cabbage, burnt garlic, and red chili oil.",
        price: 249,
        category: "Noodles & Rice",
        foodType: "Vegetarian",
        isTopRated: true,
        isRecommended: false,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Pad Thai Wok Noodles with Prawns",
        description: "Flat rice noodles stir-fried with juicy prawns, tofu, bean sprouts, crushed peanuts, and tangy tamarind lime sauce.",
        price: 399,
        category: "Noodles & Rice",
        foodType: "Non-Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1559314809-0d155014e29e?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Kung Pao Chicken with Roasted Peanuts",
        description: "Diced chicken wok-tossed with Sichuan peppercorns, dried red chilies, roasted peanuts, and spring onions.",
        price: 349,
        category: "Asian Mains",
        foodType: "Non-Vegetarian",
        isTopRated: false,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Thai Green Curry with Jasmine Rice",
        description: "Creamy coconut milk curry simmered with bamboo shoots, baby corn, zucchini, and kaffir lime leaves. Served with steamed jasmine rice.",
        price: 369,
        category: "Asian Mains",
        foodType: "Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Crispy Honey Chili Lotus Stem",
        description: "Crunchy sliced lotus root tossed in spicy honey-chili glaze and toasted white sesame seeds.",
        price: 259,
        category: "Starters",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: false,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Crispy Spring Rolls with Sweet Chili Dip (8 pcs)",
        description: "Golden rolls packed with glass noodles, shredded vegetables, and Asian seasonings.",
        price: 199,
        category: "Starters",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: false,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1548865177-3e110eb27459?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Mango Sticky Rice Coconut Delight",
        description: "Sweet glutinous sticky rice cooked in coconut cream, topped with fresh ripe mango slices and toasted sesame.",
        price: 229,
        category: "Desserts",
        foodType: "Vegan",
        isTopRated: true,
        isRecommended: true,
        isNew: true,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1621303837174-89787a7d4729?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
    ],
  },

  // 5. Green Bowl Organics & Clean Kitchen
  {
    restaurant: {
      managerId: managerMap["manager5@gmail.com"],
      restaurantName: "Green Bowl Organics & Clean Kitchen",
      description: "100% wholesome, macro-counted nutrient-dense quinoa bowls, organic superfood salads, fresh acai smoothie bowls, avocado toasts, and cold-pressed juices for healthy campus living.",
      address: "Green Arcade, Near Fitness Center & Campus Track",
      city: "Campus West",
      state: "Metro",
      pinCode: "560005",
      country: "India",
      geoLocation: { lat: "12.9680", lon: "77.5890" },
      contactDetails: { email: "hello@greenbowlorganics.com", phone: "+91 98765 43205" },
      servingHours: { openingTime: "08:00", closingTime: "21:30" },
      isOpen: true,
      status: "active",
      averageRating: 4.8,
      cuisineTypes: ["Healthy Food", "Salads", "Smoothie Bowls", "Keto", "Cold-Pressed"],
      restaurantType: "vegan",
      coverImage: {
        url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80",
        publicId: null,
      },
      restaurantImage: [
        { url: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80", publicId: null },
        { url: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=800&q=80", publicId: null },
      ],
      socialMediaLinks: [
        { platform: "Instagram", url: "https://instagram.com/greenbowlfit" },
      ],
      documents: {
        legalName: "Green Bowl Nutrition Pvt Ltd",
        companyType: "Private Limited",
        gstCertificate: "29EECU9607R1ZQ",
        fssaiCertificate: "11223344556711",
        panCard: "EECU9607R",
      },
      financialDetails: {
        bankName: "Kotak Mahindra Bank",
        accountNumber: "405011998877",
        ifscCode: "KKBK0001234",
      },
    },
    menuItems: [
      {
        itemName: "Mediterranean Quinoa & Roasted Veggie Bowl",
        description: "Organic tricolor quinoa, roasted zucchini, bell peppers, Kalamata olives, creamy feta, and lemon-tahini dressing.",
        price: 329,
        category: "Nourish Bowls",
        foodType: "Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Mexican Guacamole & Burrito Nourish Bowl",
        description: "Brown rice, spiced black beans, roasted corn, fresh guacamole, pico de gallo salsa, and lime-cilantro drizzle.",
        price: 299,
        category: "Nourish Bowls",
        foodType: "Vegan",
        isTopRated: false,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Acai Superfood Berry Smoothie Bowl",
        description: "Pure Amazonian acai blended with banana and almond milk, topped with chia seeds, toasted coconut flakes, artisan granola, and fresh berries.",
        price: 319,
        category: "Smoothie Bowls",
        foodType: "Vegan",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Avocado & Sourdough Toast with Pumpkin Seeds",
        description: "Chunky hass avocado mash on toasted artisanal sourdough, chili flakes, microgreens, and roasted crunchy pumpkin seeds.",
        price: 249,
        category: "Clean Toasts",
        foodType: "Vegan",
        isTopRated: false,
        isRecommended: true,
        isNew: true,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "High-Protein Paneer & Sprout Salad",
        description: "Grilled herbed cottage cheese cubes, sprouted moong, pomegranate arils, cucumbers, and zesty lemon honey vinaigrette.",
        price: 229,
        category: "Salads",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: false,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Cold-Pressed Green Glow Juice (300ml)",
        description: "Pure extracted juice of green apple, celery, cucumber, baby spinach, ginger, and mint. No added sugar.",
        price: 159,
        category: "Cold-Pressed Juices",
        foodType: "Vegan",
        isTopRated: true,
        isRecommended: false,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Activated Charcoal Detox Lemonade (300ml)",
        description: "Fresh lemon juice, activated coconut charcoal, organic agave nectar, and Himalayan pink salt.",
        price: 129,
        category: "Cold-Pressed Juices",
        foodType: "Vegan",
        isTopRated: false,
        isRecommended: false,
        isNew: true,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
    ],
  },

  // 6. Bean & Bloom Artisan Cafe & Bakery
  {
    restaurant: {
      managerId: managerMap["manager6@gmail.com"],
      restaurantName: "Bean & Bloom Artisan Cafe & Bakery",
      description: "Specialty single-origin pour-overs, Spanish lattes, flaky French butter croissants, all-day gourmet breakfast platters, and velvety New York cheesecakes.",
      address: "Corner Villa 3, Library Boulevard, Central Square",
      city: "Campus Central",
      state: "Metro",
      pinCode: "560001",
      country: "India",
      geoLocation: { lat: "12.9730", lon: "77.5920" },
      contactDetails: { email: "brew@beanandbloomcafe.com", phone: "+91 98765 43206" },
      servingHours: { openingTime: "07:30", closingTime: "22:30" },
      isOpen: true,
      status: "active",
      averageRating: 4.9,
      cuisineTypes: ["Cafe", "Specialty Coffee", "Bakery", "Breakfast", "Desserts"],
      restaurantType: "both",
      coverImage: {
        url: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80",
        publicId: null,
      },
      restaurantImage: [
        { url: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80", publicId: null },
        { url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80", publicId: null },
      ],
      socialMediaLinks: [
        { platform: "Instagram", url: "https://instagram.com/beanandbloomcafe" },
      ],
      documents: {
        legalName: "Bean & Bloom Roasters LLP",
        companyType: "LLP",
        gstCertificate: "29FFCU9608R1ZR",
        fssaiCertificate: "11223344556722",
        panCard: "FFCU9608R",
      },
      financialDetails: {
        bankName: "Federal Bank",
        accountNumber: "112233445566",
        ifscCode: "FDRL0001234",
      },
    },
    menuItems: [
      {
        itemName: "Spanish Iced Latte",
        description: "Double shot of single-origin espresso poured over chilled sweetened condensed milk and ice, finished with cinnamon dust.",
        price: 199,
        category: "Coffee & Brews",
        foodType: "Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Caramel Macchiato",
        description: "Freshly steamed milk with vanilla syrup, marked with espresso shots and crossed with buttery caramel drizzle.",
        price: 219,
        category: "Coffee & Brews",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1485808191679-5f86510681a2?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Fresh Butter French Croissant",
        description: "Flaky, multi-layered golden croissant baked with pure French butter, with a crisp crust and soft airy honeycomb inside.",
        price: 149,
        category: "Bakery & Bakes",
        foodType: "Vegetarian",
        isTopRated: true,
        isRecommended: false,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Almond & Dark Chocolate Croissant",
        description: "Butter croissant filled with almond frangipane cream and Belgian dark chocolate batons, topped with toasted flaked almonds.",
        price: 189,
        category: "Bakery & Bakes",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Classic English Breakfast Platter",
        description: "Two farm-fresh eggs made your way, grilled chicken sausages, baked beans, sauteed butter mushrooms, grilled tomato, and buttered toast.",
        price: 389,
        category: "All-Day Breakfast",
        foodType: "Non-Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Blueberry Glazed Baked Cheesecake",
        description: "Creamy baked Philadelphia style cheesecake on a graham cracker butter crust, finished with tart blueberry compote.",
        price: 249,
        category: "Desserts & Cakes",
        foodType: "Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Warm Walnut Fudge Brownie with Ice Cream",
        description: "Decadent dark chocolate brownie loaded with roasted walnuts, served warm with vanilla bean ice cream and fudge sauce.",
        price: 219,
        category: "Desserts & Cakes",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: false,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
    ],
  },

  // 7. Madras Tiffin Room
  {
    restaurant: {
      managerId: managerMap["manager7@gmail.com"],
      restaurantName: "Madras Tiffin Room",
      description: "Crispy golden Ghee Roast Dosas, fluffy steamed button Idlis in hot aromatic sambar, crunchy Medu Vadas, and authentic Kumbakonam Degree Filter Coffee served in traditional brass dabara.",
      address: "Heritage Block 5, Near South Gate Arch",
      city: "Campus South",
      state: "Metro",
      pinCode: "560003",
      country: "India",
      geoLocation: { lat: "12.9610", lon: "77.5870" },
      contactDetails: { email: "vanakkam@madrastiffinroom.com", phone: "+91 98765 43207" },
      servingHours: { openingTime: "07:00", closingTime: "22:00" },
      isOpen: true,
      status: "active",
      averageRating: 4.7,
      cuisineTypes: ["South Indian", "Dosa", "Tiffin", "Filter Coffee", "Pure Veg"],
      restaurantType: "veg",
      coverImage: {
        url: "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=1200&q=80",
        publicId: null,
      },
      restaurantImage: [
        { url: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80", publicId: null },
        { url: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80", publicId: null },
      ],
      socialMediaLinks: [
        { platform: "Instagram", url: "https://instagram.com/madrastiffinroom" },
      ],
      documents: {
        legalName: "Madras Tiffin Ventures Pvt Ltd",
        companyType: "Private Limited",
        gstCertificate: "29GGCU9609R1ZS",
        fssaiCertificate: "11223344556733",
        panCard: "GGCU9609R",
      },
      financialDetails: {
        bankName: "Canara Bank",
        accountNumber: "01011010023456",
        ifscCode: "CNRB0000101",
      },
    },
    menuItems: [
      {
        itemName: "Ghee Roast Masala Dosa",
        description: "Extra-crispy large fermented crepe roasted generously in pure desi ghee, filled with spiced potato masala. Served with 3 coconut chutneys and hot sambar.",
        price: 189,
        category: "Dosas & Crepes",
        foodType: "Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Cheese Burst & Podi Butter Dosa",
        description: "Crispy golden dosa smeared with spicy gunpowder (milagai podi), melted cheese, and fresh butter.",
        price: 229,
        category: "Dosas & Crepes",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: true,
        isNew: true,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Steamed Button Ghee Sambar Idlis (12 pcs)",
        description: "Mini soft fluffy rice cakes immersed in a bowl of piping hot Madras shallot sambar with a spoonful of hot ghee.",
        price: 129,
        category: "Idli & Vada",
        foodType: "Vegetarian",
        isTopRated: true,
        isRecommended: false,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Crispy Medu Vada (2 pcs)",
        description: "Crispy on the outside, fluffy on the inside fried lentil donuts served with fresh coconut chutney and spicy tomato relish.",
        price: 119,
        category: "Idli & Vada",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: false,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Traditional Kumbakonam Degree Filter Coffee",
        description: "Freshly brewed chicory-coffee decoction blended with frothy boiled milk, served in traditional brass dabara and tumbler.",
        price: 79,
        category: "Beverages",
        foodType: "Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Curd Rice with Tadka & Pomegranate",
        description: "Comforting creamy tempered curd rice with mustard seeds, curry leaves, ginger, green chilies, and sweet pomegranate arils.",
        price: 149,
        category: "Meals",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: false,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
    ],
  },

  // 8. Sip & Slurp Shake Studio & Boba Bar
  {
    restaurant: {
      managerId: managerMap["manager8@gmail.com"],
      restaurantName: "Sip & Slurp Shake Studio & Boba Bar",
      description: "Chewy Brown Sugar Tiger Milk Boba, authentic Taiwanese milk teas, towering monster thick shakes, fruit coolers, and loaded cheesy nachos.",
      address: "Shop 21, Student Activity Hub, Central Walkway",
      city: "Campus Central",
      state: "Metro",
      pinCode: "560001",
      country: "India",
      geoLocation: { lat: "12.9725", lon: "77.5935" },
      contactDetails: { email: "slurp@sipandslurp.com", phone: "+91 98765 43208" },
      servingHours: { openingTime: "11:00", closingTime: "00:30" },
      isOpen: true,
      status: "active",
      averageRating: 4.6,
      cuisineTypes: ["Boba Tea", "Thick Shakes", "Mocktails", "Sundaes", "Snacks"],
      restaurantType: "both",
      coverImage: {
        url: "https://images.unsplash.com/photo-1558857563-b371033873b8?auto=format&fit=crop&w=1200&q=80",
        publicId: null,
      },
      restaurantImage: [
        { url: "https://images.unsplash.com/photo-1525385133512-2f3bdd039054?auto=format&fit=crop&w=800&q=80", publicId: null },
        { url: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80", publicId: null },
      ],
      socialMediaLinks: [
        { platform: "Instagram", url: "https://instagram.com/sipnslurpboba" },
      ],
      documents: {
        legalName: "Sip & Slurp Beverage Co.",
        companyType: "Partnership",
        gstCertificate: "29HHCU9610R1ZT",
        fssaiCertificate: "11223344556744",
        panCard: "HHCU9610R",
      },
      financialDetails: {
        bankName: "Yes Bank",
        accountNumber: "00223344556677",
        ifscCode: "YESB0000022",
      },
    },
    menuItems: [
      {
        itemName: "Brown Sugar Tiger Milk Boba",
        description: "Slow-cooked warm tapioca pearls coated in caramelized brown sugar syrup, chilled organic milk, and rich cream cheese foam top.",
        price: 249,
        category: "Boba & Bubble Teas",
        foodType: "Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1558857563-b371033873b8?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Taro Coconut Bubble Tea",
        description: "Sweet purple taro root blended with creamy coconut milk and chewy black tapioca pearls.",
        price: 239,
        category: "Boba & Bubble Teas",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: true,
        isNew: true,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1525385133512-2f3bdd039054?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Nutella Oreo Overload Monster Shake",
        description: "Thick creamy vanilla and Nutella shake blended with crushed Oreos, topped with a whole mini donut and chocolate wafer roll.",
        price: 219,
        category: "Thick Monster Shakes",
        foodType: "Vegetarian",
        isTopRated: true,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Ferrero Rocher & Roasted Hazelnut Supreme",
        description: "Luxurious blend of crushed Ferrero chocolates, hazelnut praline spread, and dairy ice cream with chocolate drizzle.",
        price: 269,
        category: "Thick Monster Shakes",
        foodType: "Vegetarian",
        isTopRated: true,
        isRecommended: false,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1541658016709-82535e94bc69?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Mango Passion Fruit Popping Boba Cooler",
        description: "Chilled tropical cooler with juicy mango nectar, passion fruit fizz, and bursting mango popping pearls.",
        price: 199,
        category: "Fruit Coolers",
        foodType: "Vegan",
        isTopRated: false,
        isRecommended: true,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
      {
        itemName: "Loaded Cheesy Nachos with Jalapenos",
        description: "Crisp Mexican tortilla chips smothered with warm melted cheddar cheese sauce, salsa, black olives, and tangy jalapenos.",
        price: 189,
        category: "Quick Bites",
        foodType: "Vegetarian",
        isTopRated: false,
        isRecommended: false,
        isNew: false,
        status: "available",
        isAvailable: true,
        isDeleted: false,
        image: { url: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?auto=format&fit=crop&w=600&q=80", publicId: null },
      },
    ],
  },
];

export const restaurantSeed = async () => {
  try {
    console.log("🌱 Starting Restaurant & Menu seeding...");

    // Find all manager users
    const users = await User.find({ userType: "restaurant" });
    const managerMap = {};
    users.forEach((u) => {
      managerMap[u.email] = u._id;
    });

    const seedData = getRestaurantsSeedData(managerMap);

    for (const data of seedData) {
      const { restaurant: restData, menuItems } = data;

      if (!restData.managerId) {
        console.warn(`⚠️ Manager not found for restaurant ${restData.restaurantName}, finding first available restaurant user...`);
        const fallbackManager = users[0];
        if (fallbackManager) restData.managerId = fallbackManager._id;
      }

      // Check if existing restaurant with same name or manager
      const existing = await Restaurant.findOne({
        $or: [
          { restaurantName: restData.restaurantName },
          { managerId: restData.managerId },
        ],
      });

      if (existing) {
        await Menu.deleteMany({ restaurantId: existing._id });
        await existing.deleteOne();
      }

      // Create restaurant
      const createdRestaurant = await Restaurant.create(restData);

      // Create restaurant menu
      await Menu.create({
        restaurantId: createdRestaurant._id,
        menuItems: menuItems,
      });

      console.log(`✅ Seeded: ${createdRestaurant.restaurantName} (${menuItems.length} menu items)`);
    }

    console.log("🎉 All 8 Restaurants & Full Menus Seeded Successfully!");
  } catch (error) {
    console.error("❌ restaurantSeed error:", error.message);
    throw error;
  }
};

export default restaurantSeed;
